# Generated by Django 5.0.2 on 2025-07-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="payment",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="pidx",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="signature",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="transaction_uuid",
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("KHALTI", "Khalti"),
                    ("ESEWA", "eSewa"),
                    ("PENDING", "Pending"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("INITIATED", "Initiated"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("EXPIRED", "Expired"),
                    ("REFUNDED", "Refunded"),
                    ("CANCELLED", "Cancelled"),
                ],
                max_length=10,
            ),
        ),
    ]
