# Generated by Django 5.0.2 on 2025-07-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_add_transaction_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="transaction_uuid",
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
    ]
