# Generated by Django 5.0.2 on 2025-07-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("breed_finder", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="pets/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available for Adoption"),
                            ("PENDING", "Adoption Pending"),
                            ("ADOPTED", "Adopted"),
                        ],
                        default="AVAILABLE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
