# Generated by Django 5.0.2 on 2025-07-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("breed_finder", "0003_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
