# Generated by Django 5.0.2 on 2025-07-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("breed_finder", "0004_pet_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="age",
        ),
        migrations.AddField(
            model_name="pet",
            name="age_months",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pet",
            name="age_years",
            field=models.IntegerField(default=0),
        ),
    ]
